export const ADD_QUERY_ITEM = 'ADD_QUERY_ITEM';
export type ADD_QUERY_ITEM = typeof ADD_QUERY_ITEM;

export const REMOVE_QUERY_ITEM = 'REMOVE_QUERY_ITEM';
export type REMOVE_QUERY_ITEM = typeof REMOVE_QUERY_ITEM;

export const QUERY_FOR_ITEMS = 'QUERY_FOR_ITEMS';
export type QUERY_FOR_ITEMS = typeof QUERY_FOR_ITEMS;

export const RECEIVE_ITEMS = 'RECEIVE_ITEMS';
export type RECEIVE_ITEMS = typeof RECEIVE_ITEMS;

export const TYPE_FILTER_CHANGE = 'TYPE_FILTER_CHANGE';
export type TYPE_FILTER_CHANGE = typeof TYPE_FILTER_CHANGE;

export const MAIN_VIEW_TYPE_CHANGE = 'MAIN_VIEW_TYPE_CHANGE';
export type MAIN_VIEW_TYPE_CHANGE = typeof MAIN_VIEW_TYPE_CHANGE;
